### ISSUE TITLE
git clone fails in patch.sh

### ISSUE THREAD

**Issue by jadonk** [beagleboard/kernel#1]
https://github.com/beagleboard/kernel/blob/master/patch.sh#L42 generates an error on my version of git.  I need to confirm that this is resolved in newer versions of git.

**Comment by RobertCNelson** [comment]
Jason, what error is git throwing out?

Does this error only occur inside TI? If so it's probably a proxy issue, and we'd just have to set it up for corkscrew/etc/something...  Over here, using Debian Wheezy with git version 1.7.10...

Regards,

**Comment by joelagnel** [comment]
What is your version? I don't get any immediate errors.

joel@joelbox:/tmp$ git --version
git version 1.7.9.5

joel@joelbox:/tmp/1$ git clone
git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git .
Cloning into '.'...
remote: Counting objects: 298191

Joel

**Comment by jadonk** [comment]
I confirmed it works for me using a newer version of git.
