### ISSUE TITLE
MMC support using capebus isn't working

### ISSUE THREAD

**Issue by koenkooi** [beagleboard/kernel#10]
MMC hangs when capebus is used to manage it, you can only have one port active that way. This means that the eMMC cape doesn't work properly

**Comment by pantoniou** [comment]
I wouldn't say that it's the eMMC cape not working. Looks like it's first come, first served.

The first MMC device works, while the other 'hangs' on some transaction during initialization.

**Comment by jadonk** [comment]
This can be closed, right?
