### ISSUE TITLE
512MB support

### ISSUE THREAD

**Issue by jadonk** [beagleboard/kernel#15]
Support for 512MB DDR3

**Comment by RobertCNelson** [comment]
In theory, this should already be taken care of by u-boot in v2013.01-rc2:

http://git.denx.de/?p=u-boot.git;a=blob;f=board/ti/am335x/board.c;h=f0eca54c9e9626bcdd187e60d6b8b03501831f34;hb=HEAD#l301

**Comment by koenkooi** [comment]
that's DDR3, not sure if that's for 512MB instead of 256MB

**Comment by RobertCNelson** [comment]
I've read somewhere that it's auto calculated now (during the time frame when X-Loader/SPL was merged..)

CONFIG_NR_DRAM_BANKS
http://git.denx.de/?p=u-boot.git;a=blob;f=arch/arm/lib/board.c#l156

http://git.denx.de/?p=u-boot.git;a=blob;f=arch/arm/cpu/armv7/am33xx/emif4.c#l30

When I re-added C4 support to mainline when it was left/forgotten in x-loader:
http://git.denx.de/?p=u-boot.git;a=blob;f=board/ti/beagle/beagle.c;h=f20ebed4524298c4d5bb777dd732f7ae509d1b1c;hb=HEAD#l169
We didn't actually set the ram size, only the speed and nand size parameters..

Edit: maybe *mcfg is the memory size.. (it's been a while..)

**Comment by c2h2** [comment]
512MB should be taken care by u-boot, I have the same RAM chip on my custom board. works fine with the same kernel. u-boot recognize it.
