### ISSUE TITLE
make oldconfig issue when following instructions

### ISSUE THREAD

**Issue by 17twenty** [beagleboard/kernel#38]
Following the instructions after running patch.sh

the line:

> make uImage dtbs

causes lots of config questions to be asked. It looks like a make oldconfig was missed as the kernel is prompting for missing options.

What's the best thing forward on this - accept the defaults?

**Comment by RobertCNelson** [comment]
Did you copy the config from ./configs/<board> as .config before running "make ARCH=arm uImage dtbs"?

**Comment by 17twenty** [comment]
Looks like my dev environment had been screwed up and wasn't setting the ARCH correctly.
