### ISSUE TITLE
Beaglebone Black fails in installing RTL8892CU WIfi module

### ISSUE THREAD

**Issue by noisette** [beagleboard/kernel#39]
When connecting a Usb-to-Wifi adapter using Realtek chipset RTL8892CU, BeagleBone Black (Angstrom distribution 3.8.13) fails saying that the firmware rtl8892CU.bin is not available

**Comment by RobertCNelson** [comment]
Download these:

https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/tree/rtlwifi

into:
/lib/firmware/rtlwifi/

Regards,

**Comment by piranha32** [comment]
Question for Koen: Would it be possible to package the firmware files with
Angstrom?

thx,
j.

On Wed, May 15, 2013 at 5:13 PM, Robert Nelson notifications@github.comwrote:

> Download these:
> 
> https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/tree/rtlwifi
> 
> into:
> /lib/firmware/rtlwifi/
> 
> Regards,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/beagleboard/kernel/issues/39#issuecomment-17966634
> .

## 

Given a choice between two theories, take the one which is funnier

**Comment by noisette** [comment]
Hi Robert, thanks for the answer... Now i am getting : rtlwifi:rtl_fw_cb():<0-0> Firmware is too big!
See my DMESG log below...

[  321.302341] usb 1-1.6: new high-speed USB device number 9 using musb-hdrc
[  321.383097] usb 1-1.6: default language 0x0409
[  321.383482] usb 1-1.6: udev 9, busnum 1, minor = 8
[  321.383497] usb 1-1.6: New USB device found, idVendor=0bda, idProduct=8176
[  321.383510] usb 1-1.6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  321.383522] usb 1-1.6: Manufacturer: Realtek
[  321.383533] usb 1-1.6: SerialNumber: 00e04c000001
[  321.383992] usb 1-1.6: usb_probe_device
[  321.384012] usb 1-1.6: configuration #1 chosen from 1 choice
[  321.384188] usb 1-1.6: adding 1-1.6:1.0 (config #1, interface 0)
[  321.384551] rtl8192cu 1-1.6:1.0: usb_probe_interface
[  321.384569] rtl8192cu 1-1.6:1.0: usb_probe_interface - got id
[  321.384752] rtl8192cu: Chip version 0x10
[  321.436516] rtl8192cu: MAC address: 00:0b:81:89:02:09
[  321.436548] rtl8192cu: Board Type 0
[  321.436665] rtlwifi: rx_max_size 15360, rx_urb_num 8, in_ep 1
[  321.436811] rtl8192cu: Loading firmware rtlwifi/rtl8192cufw.bin
[  321.437700] rtlwifi:rtl_fw_cb():<0-0> Firmware is too big!

**Comment by noisette** [comment]
Hi Robert, never mind the las post... i copied the wrong file... it now works! Thanks so much.
Jean-Francois

**Comment by miguel-ribeiro** [comment]
Hey, noisette, I followed the exact same steps, and I'm also getting "firmware is too big!" message

You mention you copied the wrong file? What was the correct file?
I copied rtl8192cufw.bin and I'm still getting that error. Do you remember how did you fix it?

( I'm using 8192, because that is what appears in lsusb )
I really need this, Thanks
