### ISSUE TITLE
Building uImage for 3.11 with stock config fails.

### ISSUE THREAD

**Issue by Ferroin** [beagleboard/kernel#52]
When following the standard procedure to build a Linux 3.11 kernel image for a beagle bone black, the build fails with the message:

```
multiple (or no) load addresses: 
This is incompatible with uImages
Specify LOADADDR on the commandline to build an uImage
make[1]: *** [arch/arm/boot/uImage] Error 1
make: *** [uImage] Error 2
```

While this is theoretically self explanatory, `LOADADDR` is not something that should just be set arbitrarily without knowledge of the hardware and boot loader.  At the very least the documentation should be updated to reflect this needed make variable, as well as suggesting a default value for it.

**Comment by RobertCNelson** [comment]
For "omap" LOADADDR=0x80008000....

But you should "really" just start using zImage's...  But otherwise the v3.11 branch is not ready for general users yet...

Regards,

**Comment by Ferroin** [comment]
Thanks for the info, and also the warning about 3.11 being pre-production-quality; I'm pretty used to running bleeding edge kernels, so if I do find any bugs, I can probably help fix them.
