### ISSUE TITLE
Beaglebone Black support?

### ISSUE THREAD

**Issue by dvial** [beagleboard/kernel#60]
Is this meant to run on Beaglebone Black? When I attempt to run patch.sh the write fails with the message "No space left on device".

I have no files on the device except those that came with the out-of-the-box Angstrom distribution.

**Comment by RobertCNelson** [comment]
No, unless you have a spare 1.5/2GB of free space...

**Comment by tenaciousRas** [comment]
After reading this response, I wasn't sure if this is an/the official Beagleboard kernel development project, or a project by a long-ranger who likes to share.

Are the system requirements for this kernel posted online somewhere?

**Comment by RobertCNelson** [comment]
I'll let you decide: https://github.com/beagleboard/kernel/blob/master/patch.sh#L3

The "patch.sh" script, needs a lot of space as it clones the full "linux-stable" repo... The main purpose of this repo is to keep track and continuously 'rebase' all the external patches we are working on getting in mainline..

System requirements: lots of harddrive space, compiler, etc..

Edit: a minimal of 1.7GB of space is needed as of today to run this script. (it will continue to grow..)

Regards,

**Comment by dvial** [comment]
This was linked to me through a BeagleBone support thread. I was hoping to take advantage of USB patches posted here but it sounds like that isn't doable?

**Comment by RobertCNelson** [comment]
Why not? Run the script on an x86 pc, or with a much larger media device then the eMMC on the bbb, then rebuild the kernel/install/etc..

**Comment by dvial** [comment]
"Why not?" - namely because I'm new to all of this and didn't realize that's the far better practice ;) Thanks!
