### ISSUE TITLE
3.13: recipes/linux-mainline_3.13.bb missing

### ISSUE THREAD

**Issue by mrybczyn** [beagleboard/kernel#71]
./patch.sh fails, because  recipes/linux-mainline_3.13.bb is missing. The recipes directory has /linux-mainline_3.12.bb inside instead.

**Comment by RobertCNelson** [comment]
Thanks for the ping, this should fix it:
https://github.com/beagleboard/kernel/commit/8bb2662121220e5150a172b4e2848b83a27291a0

right now there is no difference between the 3.13 & 3.12 branches..
