### ISSUE TITLE
usb0 not available

### ISSUE THREAD

**Issue by kkwekkeboom** [beagleboard/kernel#74]
I use the stock emmC flasher with custom made am335x-bone.dtb, but after building and installing a new kernel (uImage) the usb0 is missing. Therefore I can't use the serial port and ethernet over serial port.

I literally followed the instructions on http://wiki.beyondlogic.org/index.php/BeagleBoneBlack_Building_Kernel#Compiling_the_BeagleBone_Black_Kernel_2

Only adjustment is in the defconfig file:
NOWAYOUT=y

**Comment by mrybczyn** [comment]
Are you sure you have installed the modules for your new kernel? If so, try to modprobe one of the modules you'd like to have manually. If there is a problem, it will be shown.

**Comment by kkwekkeboom** [comment]
lsmod shows an empty log

journalctl | grep tty shows:

```
Jan 01 00:00:02 beaglebone systemd[1]: Expecting device dev-ttyGS0.device...
Jan 01 00:00:02 beaglebone systemd[1]: Expecting device dev-ttyO0.device...
Jan 01 00:00:02 beaglebone systemd-modules-load[95]: Failed to lookup alias 'ircomm-tty': Function not implemented
Jan 01 00:00:03 beaglebone systemd[1]: Found device /dev/ttyO0.
Jan 01 00:00:08 beaglebone systemd[1]: Starting Serial Getty on ttyO0...
Jan 01 00:00:08 beaglebone systemd[1]: Started Serial Getty on ttyO0.
Jan 01 00:00:08 beaglebone systemd[1]: Starting Getty on tty1...
Jan 01 00:00:08 beaglebone systemd[1]: Started Getty on tty1.
Nov 19 13:15:42 beaglebone systemd[1]: Job dev-ttyGS0.device/start timed out.
Nov 19 13:15:42 beaglebone systemd[1]: Timed out waiting for device dev-ttyGS0.device.
Nov 19 13:15:42 beaglebone systemd[1]: Dependency failed for Serial Getty on ttyGS0.
Nov 19 13:15:42 beaglebone systemd[1]: Job serial-getty@ttyGS0.service/start failed with result 'dependency'.
Nov 19 13:15:42 beaglebone systemd[1]: Job dev-ttyGS0.device/start failed with result 'timeout'.
```

**Comment by mrybczyn** [comment]
Empty lsmod means for me that you do not have modules installed for your kernel. Also, in the log you provided there is an error when loading a module (ircom). Are you sure that you have you installed them?

Check:
uname -a
Then if the directory with the kernel version exists in /lib/modules/.

For example, in my case:
root@beaglebone:~# uname -a
Linux beaglebone 3.12.0-00080-g12cbe01 #2 SMP Mon Nov 11 16:41:45 CET 2013 armv7l GNU/Linux
root@beaglebone:~# ls /lib/modules/
3.12.0/                3.12.0-00080-g12cbe01/ 3.8.13/

The right directory is '3.12.0-00080-g12cbe01' in this case.

For reference, my lsmod at boot:
root@beaglebone:~# lsmod
Module                  Size  Used by
snd_soc_omap            2834  0 
snd_pcm_dmaengine       6069  1 snd_soc_omap
snd_soc_core          120132  1 snd_soc_omap
snd_compress            7482  1 snd_soc_core
regmap_spi              1901  1 snd_soc_core
snd_pcm                77519  3 snd_soc_core,snd_soc_omap,snd_pcm_dmaengine
snd_page_alloc          5160  1 snd_pcm
snd_timer              18758  1 snd_pcm
snd                    59763  4 snd_soc_core,snd_timer,snd_pcm,snd_compress
soundcore               6830  1 snd
ip_tables              10409  0 
x_tables               17068  1 ip_tables
usb_f_acm               5233  1 
u_serial                9720  3 usb_f_acm
g_multi                32867  0 
u_rndis                 8656  1 g_multi
u_ether                12362  1 g_multi
libcomposite           34542  2 usb_f_acm,g_multi
rfcomm                 30313  0 
ircomm_tty             17814  0 
ircomm                 10350  1 ircomm_tty
irda                  108586  2 ircomm_tty,ircomm
ipv6                  325747  12 
hidp                   13265  0 
bluetooth             199218  4 hidp,rfcomm
autofs4                22094  2 
root@beaglebone:~#

**Comment by kkwekkeboom** [comment]
Ok, then my problem is solved. I did build the kernel (replaced uImage), but did not reinstall the kernel modules (they are still installed in the /lib/modules/3.8.13 directory.
uname -a
`Linux beaglebone 3.8.13-00720-g6c7ba4e #1 SMP Fri Nov 8 15:49:14 CET 2013 armv7l GNU/Linux`

Finally, mv 3.8.13/ 3.8.13-00720-g6c7ba4e; lsmod

```
Module                  Size  Used by
g_multi                55905  2 
libcomposite           15228  1 g_multi
c_can_platform          4235  0 
c_can                   7428  1 c_can_platform
can_dev                 7992  1 c_can
rfcomm                 25106  0 
mtnet7601Usta          25701  0 
mt7601Usta            753921  1 mtnet7601Usta
mtutil7601Usta         65890  2 mt7601Usta,mtnet7601Usta
ircomm_tty             14503  0 
ircomm                  8846  1 ircomm_tty
irda                   89974  2 ircomm_tty,ircomm
ipv6                  229989  8 
hidp                   10112  0 
bluetooth             146100  4 hidp,rfcomm
rfkill                 16510  1 bluetooth
autofs4                17432  2 
```

ifconfig

```
ifconfig
eth0      Link encap:Ethernet  HWaddr C8:A0:30:A6:B2:4B  
          inet addr:192.168.140.113  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::caa0:30ff:fea6:b24b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:17 errors:0 dropped:7 overruns:0 frame:0
          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2820 (2.7 KiB)  TX bytes:6991 (6.8 KiB)
          Interrupt:56 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

usb0      Link encap:Ethernet  HWaddr FE:71:71:BC:C7:77  
          inet addr:192.168.7.2  Bcast:192.168.7.3  Mask:255.255.255.252
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
