### ISSUE TITLE
kernel build 3.12 fails

### ISSUE THREAD

**Issue by chow04** [beagleboard/kernel#93]
I acquire the kernel and patch it via the commands:

git clone https://github.com/beagleboard/kernel.git 3.12
cd 3.12
git checkout origin/3.12 -b 3.12
./patch.sh

Then when I attempt to compile the kernel:

cd kernel
cp ../configs/beaglebone .config
mkdir rootfs
make ARCH=arm CROSS_COMPILE=arm-angstrom-linux-gnueabi- LOADADDR=0x80008000 uImage dtsbs

I get the following output:

  CHK         include/config/kernel.release
  CHK         include/generated/uapi/linux/version.h
  CHK         include/generated/utsrelease.h
make[1]:   `include/generated/mach-types.h'  is up to date.
  CALL       scripts/checksyscalls.sh
  CHK         include/generated/compile.h
  CC           arch/arm/kernel/signal.o
/tmp/ccScLcjY.s: Assembler messages:
/tmp/ccScLcjY.s:945: Error: garbage following instruction --`dmb ish'
make[1]: **\* [arch/arm/kernel/signal.o] Error 1
make: **\* [arch/arm/kernel] Error 2

I'm building using Ubuntu 12.04
gcc --version outputs:
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

**Comment by RobertCNelson** [comment]
Binutils is too old.
